- name: Ensure cryptsetup is installed
  apt:
    name: cryptsetup
    state: present

- name: Create a LUKS key file from Ansible Vault content
  copy:
    dest: "{{ key_file }}"
    content: "{{ luks_key_content }}"
    owner: root
    group: root
    mode: "0600"

- name: Check if the disk is already encrypted
  shell: cryptsetup isLuks {{ disk_to_encrypt }}
  register: luks_status
  ignore_errors: true

- name: Format the disk with LUKS encryption using the key file
  community.crypto.luks_device:
    device: "{{ disk_to_encrypt }}"
    state: present
    keyfile: "{{ key_file }}"
    label: "{{ encrypted_name }}"
  when: luks_status.rc != 0

- name: Check if the encrypted device is already open
  shell: ls /dev/mapper/{{ encrypted_name }}
  register: encrypted_device_status
  ignore_errors: true

- name: Open the LUKS encrypted disk using the key file
  community.crypto.luks_device:
    device: "{{ disk_to_encrypt }}"
    state: opened
    name: "{{ encrypted_name }}"
    keyfile: "{{ key_file }}"
  when: encrypted_device_status.rc != 0

- name: Disk information
  shell: lsblk -f {{ disk_to_encrypt }}
  register: disk_info

- name: Encryption dump
  shell: cryptsetup luksDump {{ disk_to_encrypt }}
  register: luks_dump

- name: Debug disk information
  debug:
    msg: "Disk is encrypted {{ disk_info.stdout }}"

# - name: Debug encryption dump
#   debug:
#     msg: "{{ luks_dump.stdout }}"