- name: Ensure cryptsetup is installed
  apt:
    name: cryptsetup
    state: present

###### CLEARS THE PARTITION ######
- name: Ensure the partition is clean
  shell: dd if=/dev/zero of={{ partition_to_encrypt }} bs=512 count=4
  ignore_errors: true
  when: partition_to_encrypt is defined

- name: Create a LUKS key file from Ansible Vault content
  copy:
    dest: "{{ key_file }}"
    content: "{{ luks_key_content }}"
    owner: root
    group: root
    mode: "0600"

- name: Set up LUKS encryption on the partition
  community.crypto.luks_device:
    device: "{{ partition_to_encrypt }}"
    state: present
    keyfile: "{{ key_file }}"
    type: luks1
    pbkdf: 
      iteration_count: 1000

- name: Open the LUKS encrypted partition
  community.crypto.luks_device:
    device: "{{ partition_to_encrypt }}"
    state: opened
    keyfile: "{{ key_file }}"
    name: "{{ encrypted_name }}"

- name: Ensure disk is encrypted
  shell: lsblk -f {{ partition_to_encrypt }}
  register: disk_info

- name: Debug disk information
  debug:
    msg: "Disk is encrypted {{ disk_info.stdout }}"

- name: Close the LUKS encrypted partition
  community.crypto.luks_device:
    state: "closed"
    name: "{{ encrypted_name }}"
